name: CI - Dev Branch

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/core-setup
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          direct-url: ${{ secrets.DIRECT_URL }}

      - name: Type check
        run: npm run typecheck

      - name: Lint
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup project
        uses: ./.github/actions/core-setup
        with:
          database-url: ${{ secrets.DATABASE_URL }}
          direct-url: ${{ secrets.DIRECT_URL }}

      - name: Build project
        run: npm run build
